const products = [
  {
    title: "Berryville Hostel",
    categoryId: "",
    categoryName: "Accommodation",
    adStatus: "Active",
    school: "UNILAG",
    price: "350000",
    paymentPeriod: "Year",
    type: "one man room",
    bedrooms: "1",
    bathrooms: "1",
    toilets: "1",
    generator: true,
    airConditioner: true,
    studyRoom: true,
    tvRoom: true,
    delivery: true,
    "wi-fi": true,
    furnished: true,
    description: `randomo description with lorem ipsum`,
    address: `25, Unilag Road, Abule-Oja Bus-Stop, Yaba, Lagos`,
  },
  {
    title: "Ozolua",
    categoryId: "",
    categoryName: "Accommodation",
    adStatus: "Active",
    school: "UNILAG",
    price: "350000",
    paymentPeriod: "Year",
    type: "one man room",
    bedrooms: "1",
    delivery: true,
    bathrooms: "1",
    toilets: "1",
    generator: true,
    airConditioner: true,
    studyRoom: true,
    tvRoom: true,
    "wi-fi": true,
    furnished: true,
    description: `randomo description with lorem ipsum`,
    address: `25, Unilag Road, Abule-Oja Bus-Stop, Yaba, Lagos`,
  },
  {
    title: "High Rise",
    categoryId: "",
    categoryName: "Accommodation",
    adStatus: "Active",
    school: "UNILAG",
    price: "350000",
    paymentPeriod: "Year",
    type: "one man room",
    bedrooms: "1",
    delivery: true,
    bathrooms: "1",
    toilets: "1",
    generator: true,
    airConditioner: true,
    studyRoom: true,
    tvRoom: true,
    "wi-fi": true,
    furnished: true,
    description: `randomo description with lorem ipsum`,
    address: `25, Unilag Road, Abule-Oja Bus-Stop, Yaba, Lagos`,
  },
  {
    title: "Diamond Hostel",
    categoryId: "",
    categoryName: "Accommodation",
    adStatus: "Active",
    school: "UNILAG",
    price: "350000",
    paymentPeriod: "Year",
    type: "one man room",
    bedrooms: "1",
    bathrooms: "1",
    toilets: "1",
    delivery: true,

    generator: true,
    airConditioner: true,
    studyRoom: true,
    tvRoom: true,
    "wi-fi": true,
    furnished: true,
    description: `randomo description with lorem ipsum`,
    address: `25, Unilag Road, Abule-Oja Bus-Stop, Yaba, Lagos`,
  },
  {
    title: "Mirabel Hostel",
    categoryId: "",
    categoryName: "Accommodation",
    adStatus: "Active",
    school: "UNILAG",
    price: "350000",
    paymentPeriod: "Year",
    type: "one man room",
    bedrooms: "1",
    delivery: true,

    bathrooms: "1",
    toilets: "1",
    generator: true,
    airConditioner: false,
    studyRoom: true,
    tvRoom: true,
    "wi-fi": true,
    furnished: false,
    description: `randomo description with lorem ipsum`,
    address: `25, Unilag Road, Abule-Oja Bus-Stop, Yaba, Lagos`,
  },
];
