const services = [
  {
    title: "Apple IPhone X 64GB White",
    categoryId: "",
    categoryName: "Mobile Phones",
    adStatus: "Active",
    school: "UNIBEN",
    price: "210000",
    brand: "Apple",
    model: "IPhone X",
    storageCapacity: "64GB",
    RAM: "3GB",
    screenSize: "5.1-6 inches",
    color: "white",
    operatingSystem: "iOS",
    SIMType: "Single Nano-SIM",
    cardSlot: false,
    mainCamera: "!2MP",
    selfieCamera: "7MP",
    battery: `2942`,
    description: "Lorem Ipsum dolor sit amet, consectetur adipisciing ",
    address: `25, Unilag Road, Abule-Oja Bus-Stop, Yaba, Lagos`,
    delivery: true,
    deliveryFee: "1000",
    deliveryTime: `within 24 hours`,
  },
  {
    title: "Samsung Galaxy Note 10 plus 256GB",
    categoryId: "",
    categoryName: "Accommodation",
    adStatus: "Active",
    school: "UNIBEN",
    price: "210000",
    brand: "Apple",
    model: "IPhone X",
    storageCapacity: "64GB",
    RAM: "3GB",
    screenSize: "5.1-6 inches",
    color: "white",
    operatingSystem: "iOS",
    SIMType: "Single Nano-SIM",
    cardSlot: false,
    mainCamera: "!2MP",
    selfieCamera: "7MP",
    battery: `2942`,
    description: "Lorem Ipsum dolor sit amet, consectetur adipisciing ",
    address: `25, Unilag Road, Abule-Oja Bus-Stop, Yaba, Lagos`,
    delivery: true,
    deliveryFee: "1000",
    deliveryTime: `within 24 hours`,
  },
];
